openapi: 3.0.0
info:
  title: Test d'orientation du COVID19
  version: '2020-04-04T21:23:52.742194Z'
servers:
  - url: 'http://localhost:4000'
    variables: {}
paths:
  /questionnaire:
    post:
      parameters:
        - description: Token to send the questionnaire
          in: header
          name: x-token
          required: true
          schema:
            type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionnaireResponse'
          description: Questionnaire
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
        '407':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
        '451':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
      tags: []
      callbacks: {}
      deprecated: false
      description: Évaluer le test d'orientation du COVID19
      operationId: QuestionnaireController.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionnaireRequest'
        description: Paramètres du test d'orientation
        required: true
      summary: Évaluer le test d'orientation du COVID19
  /token:
    post:
      parameters: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
          description: Questionnaire
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
        '407':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
      tags: []
      callbacks: {}
      deprecated: false
      description: Create a token
      operationId: TokenController.create
      summary: Create a token
components:
  responses: {}
  schemas:
    Calculations:
      description: >-
        [Calculations](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/implementation.org#conseils-pour-limpl%C3%A9mentation-de-lalgorithme)
      example:
        age_less_15: true
        age_less_50: true
        age_less_70: true
        age_more_15: true
        age_more_50: true
        age_more_70: true
        bmi: 21.9
        bmi_algo: 21.9
        bmi_less_30: true
        bmi_more_30: true
        fever_algo: true
        gravity_factors: 3
        gravity_factors_major: 1
        gravity_factors_minor: 2
        heart_disease_algo: true
        imc: 21.9
        imc_algo: 21.9
        immunosuppressant_disease_algo: true
        immunosuppressant_drug_algo: true
        pregnant_algo: true
        risk_factors: 1
        symptoms1: true
        symptoms2: true
        symptoms3: true
        symptoms4: true
      properties:
        age_less_15:
          description: Si la personne a age_less_15
          type: boolean
        age_less_50:
          description: Si la personne a age_less_50
          type: boolean
        age_less_70:
          description: Si la personne a age_less_70
          type: boolean
        age_more_15:
          description: Si la personne a age_more_15
          type: boolean
        age_more_50:
          description: Si la personne a age_more_50
          type: boolean
        age_more_70:
          description: Si la personne a age_more_70
          type: boolean
        bmi:
          description: BMI de la personne en kg/(cm/100)2
          type: number
        bmi_algo:
          description: BMI de la personne en kg/(cm/100)2
          type: number
        bmi_less_30:
          description: Moins 30 d'IMC en kg/(cm/100)2
          type: boolean
        bmi_more_30:
          description: Au moins 30 d'IMC en kg/(cm/100)2
          type: boolean
        fever_algo:
          description: Si la personne a de la fièvre
          type: boolean
        gravity_factors:
          description: Facteurs de gravité mineurs + majeurs
          type: integer
        gravity_factors_major:
          description: Facteurs de gravité majeurs
          type: integer
        gravity_factors_minor:
          description: Facteurs de gravité mineurs
          type: integer
        heart_disease_algo:
          description: Maladie cardiaque
          type: boolean
        imc:
          description: IMC de la personne en kg/(cm/100)2
          type: number
        imc_algo:
          description: IMC de la personne en kg/(cm/100)2
          type: number
        immunosuppressant_disease_algo:
          description: Maladie défenses immunitaires
          type: boolean
        immunosuppressant_drug_algo:
          description: Traitement immunodépresseur
          type: boolean
        pregnant_algo:
          description: Si la personne est enceinte
          type: boolean
        risk_factors:
          description: Facteurs pronostique défavorables liés au terrain
          type: integer
        symptoms1:
          description: Fièvre ET toux
          type: boolean
        symptoms2:
          description: >-
            Fièvre OU (pas de fièvre et (diarrhée OU (toux ET douleurs) OU (toux
            ET anosmie))
          type: boolean
        symptoms3:
          description: Toux OU douleurs OU anosmie
          type: boolean
        symptoms4:
          description: NI toux NI douleurs NI anosmie
          type: boolean
      required:
        - age_less_15
        - age_less_50
        - age_less_70
        - age_more_15
        - age_more_50
        - age_more_70
        - bmi_less_30
        - bmi_more_30
        - bmi
        - bmi_algo
        - imc
        - imc_algo
        - pregnant_algo
        - fever_algo
        - heart_disease_algo
        - immunosuppressant_disease_algo
        - immunosuppressant_drug_algo
        - symptoms1
        - symptoms2
        - symptoms3
        - symptoms4
        - gravity_factors
        - gravity_factors_minor
        - gravity_factors_major
        - risk_factors
      title: Calculations
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Calculations
    Error:
      description: Something bad happened!
      example:
        info: 'Oopsie, we don''t know what happened!'
        action: >-
          Please open an issue
          https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-elixir/issues/new
        code: 500
        stacktrace:
          kind: 'Error, error!'
          why: DKN! DKN!
      properties:
        info:
          description: Explanation of what happened
          type: string
        action:
          description: Recommended action to fix/solve the problem
          type: string
        code:
          description: HTTP status code
          type: integer
        stacktrace:
          description: Additional information for developers
          type: object
      required:
        - code
        - info
        - action
      title: Error
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Error
    ErrorResponse:
      description: Something bad happened!
      example:
        error:
          info: 'Oopsie, we don''t know what happened!'
          action: >-
            Please open an issue
            https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-elixir/issues/new
          code: 500
          stacktrace:
            kind: 'Error, error!'
            why: DKN! DKN!
      properties:
        error:
          $ref: '#/components/schemas/Error'
      title: ErrorResponse
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.ErrorResponse
    Metadata:
      description: >-
        [Caractéristiques du
        questionnaire](https://docs.google.com/spreadsheets/d/1Ne7QEp_oMHRxxYhqT56AWugfTaywu-cNRZsWPrMGvkY/edit#gid=0)
      example:
        algo_version: '2020-04-04T13:24:44.389249Z'
        date: '2020-04-04T13:24:44.389249Z'
        duration: 3600
        form_version: '2020-04-04T13:24:44.389249Z'
      properties:
        algo_version:
          description: Version de l’algorithme
          format: date-time
          type: string
        date:
          description: Date de saisie
          format: date-time
          type: string
        duration:
          description: Durée de saisie en secondes
          type: integer
        form_version:
          description: Version du formulaire
          format: date-time
          type: string
      required:
        - form_version
        - algo_version
      title: Metadata
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Metadata
    Orientation:
      description: >-
        [Orientation du questionnaire
        COVID19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#conclusions-possibles)
      example:
        code: orientation_SAMU
      properties:
        code:
          description: >-
            [Orientations
            possibles](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#conclusions-possibles)
          enum:
            - orientation_moins_de_15_ans
            - orientation_domicile_surveillance_1
            - orientation_consultation_surveillance_1
            - orientation_consultation_surveillance_2
            - orientation_SAMU
            - orientation_consultation_surveillance_3
            - orientation_consultation_surveillance_4
            - orientation_surveillance
          type: string
      required:
        - code
      title: Orientation
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Orientation
    Questionnaire:
      description: >-
        [Algorithme d'orientation du
        COVID19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#pr%C3%A9sentation-de-lalgorithme-dquestionnaire-covid19)
      example:
        calculations:
          age_less_15: true
          age_less_50: true
          age_less_70: true
          age_more_15: true
          age_more_50: true
          age_more_70: true
          bmi: 21.9
          bmi_algo: 21.9
          bmi_less_30: true
          bmi_more_30: true
          fever_algo: true
          gravity_factors: 3
          gravity_factors_major: 1
          gravity_factors_minor: 2
          heart_disease_algo: true
          imc: 21.9
          imc_algo: 21.9
          immunosuppressant_disease_algo: true
          immunosuppressant_drug_algo: true
          pregnant_algo: true
          risk_factors: 1
          symptoms1: true
          symptoms2: true
          symptoms3: true
          symptoms4: true
        metadata:
          algo_version: '2020-04-04T13:24:44.389249Z'
          date: '2020-04-04T13:24:44.389249Z'
          duration: 3600
          form_version: '2020-04-04T13:24:44.389249Z'
        orientation:
          code: orientation_SAMU
        respondent:
          age_range: sup_70
          height: 173
          postal_code: '75000'
          weight: 65.5
        risk_factors:
          breathing_disease: true
          cancer: true
          diabetes: true
          heart_disease: 1
          immunosuppressant_disease: 1
          immunosuppressant_drug: 1
          kidney_disease: true
          liver_disease: true
          pregnant: 1
        symptoms:
          agueusia_anosmia: true
          breathlessness: true
          cough: true
          diarrhea: true
          feeding_day: true
          fever: 999
          sore_throat_aches: true
          temperature_cat: 35.5-37.7
          tiredness: true
          tiredness_details: true
        token:
          date: '2020-03-29 15:20:11.875767Z'
          uuid: c9e77845-83cf-4891-88d6-804d659e81c5
      properties:
        calculations:
          $ref: '#/components/schemas/Calculations'
        metadata:
          $ref: '#/components/schemas/Metadata'
        orientation:
          $ref: '#/components/schemas/Orientation'
        respondent:
          $ref: '#/components/schemas/Respondent'
        risk_factors:
          $ref: '#/components/schemas/RiskFactors'
        symptoms:
          $ref: '#/components/schemas/Symptoms'
        token:
          $ref: '#/components/schemas/Token'
      required:
        - metadata
        - respondent
        - symptoms
        - risk_factors
      title: Questionnaire
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Questionnaire
    QuestionnaireRequest:
      description: Corps de la requête POST pour lancer l'algorithme d'orientation
      example:
        questionnaire:
          metadata:
            algo_version: '2020-04-04T13:24:44.389249Z'
            form_version: '2020-04-04T13:24:44.389249Z'
          respondent:
            age_range: sup_70
            height: 173
            postal_code: '75000'
            weight: 65.5
          risk_factors:
            breathing_disease: true
            cancer: true
            diabetes: true
            heart_disease: 1
            immunosuppressant_disease: 1
            immunosuppressant_drug: 1
            kidney_disease: true
            liver_disease: true
            pregnant: 1
          symptoms:
            agueusia_anosmia: true
            breathlessness: true
            cough: true
            diarrhea: true
            feeding_day: true
            fever: 999
            sore_throat_aches: true
            temperature_cat: 35.5-37.7
            tiredness: true
            tiredness_details: true
      properties:
        questionnaire:
          anyOf:
            - $ref: '#/components/schemas/Questionnaire'
      required:
        - questionnaire
      title: QuestionnaireRequest
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.QuestionnaireRequest
    QuestionnaireResponse:
      description: Réponse de l'algorithme d'orientation
      example:
        data:
          calculations:
            age_less_15: false
            age_less_50: false
            age_less_70: false
            age_more_15: true
            age_more_50: true
            age_more_70: true
            bmi: 21.9
            bmi_algo: 21.9
            bmi_less_30: true
            bmi_more_30: false
            fever_algo: true
            gravity_factors: 4
            gravity_factors_major: 2
            gravity_factors_minor: 2
            heart_disease_algo: true
            imc: 21.9
            imc_algo: 21.9
            immunosuppressant_disease_algo: true
            immunosuppressant_drug_algo: true
            pregnant_algo: true
            risk_factors: 10
            symptoms1: true
            symptoms2: true
            symptoms3: true
            symptoms4: false
          metadata:
            algo_version: '2020-04-04T13:24:44.389249Z'
            date: '2020-04-04T13:24:44.389249Z'
            duration: 1
            form_version: '2020-04-04T13:24:44.389249Z'
          orientation:
            code: orientation_SAMU
          respondent:
            age_range: sup_70
            height: 173
            postal_code: '75000'
            weight: 65.5
          risk_factors:
            breathing_disease: true
            cancer: true
            diabetes: true
            heart_disease: 1
            immunosuppressant_disease: 1
            immunosuppressant_drug: 1
            kidney_disease: true
            liver_disease: true
            pregnant: 1
          symptoms:
            agueusia_anosmia: true
            breathlessness: true
            cough: true
            diarrhea: true
            feeding_day: true
            fever: 999
            sore_throat_aches: true
            temperature_cat: 35.5-37.7
            tiredness: true
            tiredness_details: true
          token:
            date: '2020-04-04T13:24:44.389249Z'
            uuid: c9e77845-83cf-4891-88d6-804d659e81c5
      properties:
        data:
          $ref: '#/components/schemas/Questionnaire'
      title: QuestionnaireResponse
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.QuestionnaireResponse
    Respondent:
      description: >-
        [Caractéristiques du
        respondent](https://docs.google.com/spreadsheets/d/1Ne7QEp_oMHRxxYhqT56AWugfTaywu-cNRZsWPrMGvkY/edit#gid=0)
      example:
        age_range: sup_70
        height: 173
        postal_code: '75000'
        weight: 65.5
      properties:
        age_range:
          description: Tranche d’âge
          enum:
            - inf_15
            - from_15_to_49
            - from_50_to_69
            - sup_70
          type: string
        height:
          description: Quelle est votre taille en centimètres ?
          type: integer
        postal_code:
          description: Le code postal
          type: string
        weight:
          description: Quel est votre poids en kilogrammes ?
          type: number
      title: Respondent
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Respondent
    RiskFactors:
      description: >-
        [Questions sur les facteurs risk_factors défavorables au
        terrain](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-facteurs-risk_factors-d%C3%A9favorables-au-terrain)
      example:
        breathing_disease: true
        cancer: true
        diabetes: true
        heart_disease: 1
        immunosuppressant_disease: 1
        immunosuppressant_drug: 1
        kidney_disease: true
        liver_disease: true
        pregnant: 1
      properties:
        breathing_disease:
          description: Maladie respiratoire
          type: boolean
        cancer:
          description: Cancer actuel ou < moins de 3 ans
          type: boolean
        diabetes:
          description: Diabète
          type: boolean
        heart_disease:
          description: Maladie cardiaque
          enum:
            - 0
            - 1
            - 999
          type: integer
        immunosuppressant_disease:
          description: Maladie défenses immunitaires
          enum:
            - 0
            - 1
            - 999
          type: integer
        immunosuppressant_drug:
          description: Traitement immunodépresseur
          enum:
            - 0
            - 1
            - 999
          type: integer
        kidney_disease:
          description: Insuffisance rénale
          type: boolean
        liver_disease:
          description: Maladie chronique du foie
          type: boolean
        pregnant:
          description: Enceinte
          enum:
            - 0
            - 1
            - 888
          type: integer
      title: RiskFactors
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.RiskFactors
    Symptoms:
      description: >-
        [Questions sur les
        symptômes](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-sympt%C3%B4mes)
      example:
        agueusia_anosmia: true
        breathlessness: true
        cough: true
        diarrhea: true
        feeding_day: true
        fever: 999
        sore_throat_aches: true
        temperature_cat: 35.5-37.7
        tiredness: true
        tiredness_details: true
      properties:
        agueusia_anosmia:
          description: Perte de goût et d’odorat
          type: boolean
        breathlessness:
          description: Essoufflement
          type: boolean
        cough:
          description: Toux
          type: boolean
        diarrhea:
          description: Diarrhée
          type: boolean
        feeding_day:
          description: Difficulté pour manger/boire
          type: boolean
        fever:
          description: Fièvre
          enum:
            - 0
            - 1
            - 999
          type: integer
        sore_throat_aches:
          description: Mal de gorge ou douleurs
          type: boolean
        temperature_cat:
          description: Catégorie de température
          enum:
            - inf_35.5
            - 35.5-37.7
            - 37.7-38.9
            - sup_39
            - NSP
          type: string
        tiredness:
          description: Fatigue
          type: boolean
        tiredness_details:
          description: Alitement >=50% du temps diurne
          type: boolean
      title: Symptoms
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Symptoms
    Token:
      description: Token
      example:
        date: '2020-04-04T13:24:44.389249Z'
        uuid: c9e77845-83cf-4891-88d6-804d659e81c5
      properties:
        date:
          description: Date de crátion du token
          format: date-time
          type: string
        uuid:
          description: UUID du token
          format: uuid
          type: string
      title: Token
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Token
    TokenResponse:
      description: TokenResponse
      example:
        data:
          date: '2020-03-29 15:20:11.875767Z'
          uuid: c9e77845-83cf-4891-88d6-804d659e81c5
      properties:
        data:
          $ref: '#/components/schemas/Token'
      title: TokenResponse
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.TokenResponse
security: []
tags: []

