openapi: 3.0.0
info:
  title: Test d'orientation du Covid-19
  version: '2020-03-30 20:01:39.836837Z'
servers:
  - url: 'http://localhost:4000'
    variables: {}
paths:
  /questionnaire:
    post:
      parameters: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionnaireResponse'
          description: Questionnaire
      tags: []
      callbacks: {}
      deprecated: false
      description: Évaluer le test d'orientation du Covid-19
      operationId: QuestionnaireController.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionnaireRequest'
        description: Paramètres du test d'orientation
        required: true
      summary: Évaluer le test d'orientation du Covid-19
components:
  responses: {}
  schemas:
    Conclusion:
      description: >-
        [Conclusion de l'questionnaire du
        Covid-19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#conclusions-possibles)
      example:
        code: questionnaire_SAMU
      properties:
        code:
          description: >-
            [Conclusions
            possibles](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#conclusions-possibles)
          enum:
            - questionnaire_SAMU
            - FIN2
            - FIN3
            - FIN4
            - FIN5
            - FIN6
            - FIN7
            - FIN8
            - FIN9
          type: string
      required:
        - code
      title: Conclusion
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Conclusion
    Questionnaire:
      description: >-
        [Algorithme d'orientation du
        Covid-19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#pr%C3%A9sentation-de-lalgorithme-dquestionnaire-covid19)
      example:
        conclusion:
          code: questionnaire_SAMU
        date: '2020-03-29 15:20:11.875767Z'
        pronostiques:
          age: 70
          breathing_disease: true
          cancer: true
          diabetes: true
          heart_disease: true
          height: 1.73
          immunodeprime: true
          immunosuppressant_drug: true
          kidney_disease: true
          liver_disease: true
          pregnant: true
          weight: 65.5
        statistiques:
          au_moins_30_imc: true
          au_moins_39_de_temperature: true
          au_moins_50_ans: false
          au_moins_70_ans: true
          entre_50_et_69_ans: false
          facteurs_gravite: 3
          facteurs_gravite_majeurs: 1
          facteurs_gravite_mineurs: 2
          facteurs_pronostique: 1
          fever: true
          heart_disease: true
          moins_de_15_ans: false
          moins_de_50_ans: false
          moins_de_70_ans: false
        supplementaires:
          postal_code: '75000'
        symptomes:
          agueusia_anosmia: true
          breathlessness: true
          cough: true
          diarrhea: true
          feeding: true
          sore_throat_aches: true
          temperature: 37.5
          tiredness: true
        uuid: 5976423a-ee35-11e3-8569-14109ff1a304
      properties:
        conclusion:
          $ref: '#/components/schemas/Conclusion'
        date:
          description: Date du test d'orientation
          format: date-time
          type: string
        pronostiques:
          $ref: '#/components/schemas/Pronostiques'
        statistiques:
          $ref: '#/components/schemas/Statistiques'
        supplementaires:
          $ref: '#/components/schemas/Supplementaires'
        symptomes:
          $ref: '#/components/schemas/Symptomes'
        uuid:
          description: Id du test d'orientation
          format: uuid1
          type: string
      required:
        - symptomes
        - pronostiques
        - supplementaires
      title: Questionnaire
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Questionnaire
    QuestionnaireRequest:
      description: Corps de la requête POST pour lancer l'algorithme d'orientation
      example:
        questionnaire:
          pronostiques:
            age: 70
            breathing_disease: true
            cancer: true
            diabetes: true
            heart_disease: true
            height: 1.73
            immunodeprime: true
            immunosuppressant_drug: true
            kidney_disease: true
            liver_disease: true
            pregnant: true
            weight: 65.5
          supplementaires:
            postal_code: '75000'
          symptomes:
            agueusia_anosmia: true
            breathlessness: true
            cough: true
            diarrhea: true
            feeding: true
            sore_throat_aches: true
            temperature: 37.5
            tiredness: true
      properties:
        questionnaire:
          anyOf:
            - $ref: '#/components/schemas/Questionnaire'
      required:
        - questionnaire
      title: QuestionnaireRequest
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.QuestionnaireRequest
    QuestionnaireResponse:
      description: Réponse de l'algorithme d'orientation
      example:
        data:
          conclusion:
            code: questionnaire_SAMU
          date: '2020-03-29 15:20:11.875767Z'
          pronostiques:
            age: 70
            breathing_disease: true
            cancer: true
            diabetes: true
            heart_disease: true
            height: 1.73
            immunodeprime: true
            immunosuppressant_drug: true
            kidney_disease: true
            liver_disease: true
            pregnant: true
            weight: 65.5
          statistiques:
            au_moins_30_imc: true
            au_moins_39_de_temperature: true
            au_moins_50_ans: false
            au_moins_70_ans: true
            entre_50_et_69_ans: false
            facteurs_gravite: 3
            facteurs_gravite_majeurs: 1
            facteurs_gravite_mineurs: 2
            facteurs_pronostique: 1
            fever: true
            heart_disease: true
            moins_de_15_ans: false
            moins_de_50_ans: false
            moins_de_70_ans: false
          supplementaires:
            postal_code: '75000'
          symptomes:
            agueusia_anosmia: true
            breathlessness: true
            cough: true
            diarrhea: true
            feeding: true
            sore_throat_aches: true
            temperature: 37.5
            tiredness: true
          uuid: 5976423a-ee35-11e3-8569-14109ff1a304
      properties:
        data:
          $ref: '#/components/schemas/Questionnaire'
      title: QuestionnaireResponse
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.QuestionnaireResponse
    Pronostiques:
      description: >-
        [Questions sur les facteurs pronostiques défavorables au
        terrain](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-facteurs-pronostiques-d%C3%A9favorables-au-terrain)
      example:
        age: 70
        breathing_disease: true
        cancer: true
        diabetes: true
        heart_disease: true
        height: 1.73
        immunodeprime: true
        immunosuppressant_drug: true
        kidney_disease: true
        liver_disease: true
        pregnant: true
        weight: 65.5
      properties:
        age:
          description: Quel est votre âge ?
          type: integer
        breathing_disease:
          description: >-
            Avez-vous une maladie respiratoire ? Ou êtes-vous suivi par un
            pneumologue ?
          type: boolean
        cancer:
          description: Avez-vous ou avez-vous eu un cancer ?
          type: boolean
        diabetes:
          description: Êtes-vous diabétique ?
          type: boolean
        heart_disease:
          description: >-
            Avez-vous une tension artérielle mal équilibrée ? Ou une maladie
            cardiaque ou vasculaire ? Ou prenez-vous un traitement à visée
            cardiologique ?
          type: boolean
        height:
          description: Quelle est votre taille en mètres ?
          type: number
        immunodeprime:
          description: >-
            Avez-vous une maladie connue pour diminuer vos défenses immunitaires
            ?
          type: boolean
        immunosuppressant_drug:
          description: Prenez-vous un traitement immunosuppresseur ?
          type: boolean
        kidney_disease:
          description: Avez-vous une insuffisance rénale chronique dialysée ?
          type: boolean
        liver_disease:
          description: Avez-vous une maladie chronique du foie ?
          type: boolean
        pregnant:
          description: Êtes-vous enceinte ?
          type: boolean
        weight:
          description: Quel est votre poids en kilogrammes ?
          type: number
      title: Pronostiques
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Pronostiques
    Statistiques:
      description: >-
        [Statistiques](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/implementation.org#conseils-pour-limpl%C3%A9mentation-de-lalgorithme)
      example:
        au_moins_30_imc: true
        au_moins_39_de_temperature: true
        au_moins_50_ans: false
        au_moins_70_ans: true
        entre_50_et_69_ans: false
        facteurs_gravite: 3
        facteurs_gravite_majeurs: 1
        facteurs_gravite_mineurs: 2
        facteurs_pronostique: 1
        fever: true
        heart_disease: true
        moins_de_15_ans: false
        moins_de_50_ans: false
        moins_de_70_ans: false
      properties:
        au_moins_30_imc:
          description: Si la personne a au moins 30 d'IMC en kg/m2
          type: boolean
        au_moins_39_de_temperature:
          description: Si la personne a au moins 39°C de température
          type: boolean
        au_moins_50_ans:
          description: Si la personne a au moins 50 ans
          type: boolean
        au_moins_70_ans:
          description: Si la personne a au moins de 70 ans
          type: boolean
        entre_50_et_69_ans:
          description: Si la personne a entre 50 et 69 ans
          type: boolean
        facteurs_gravite:
          description: Facteurs de gravité mineurs + majeurs
          type: integer
        facteurs_gravite_majeurs:
          description: Facteurs de gravité majeurs
          type: integer
        facteurs_gravite_mineurs:
          description: Facteurs de gravité mineurs
          type: integer
        facteurs_pronostique:
          description: Facteurs pronostique défavorables liés au terrain
          type: integer
        fever:
          description: Indicateur de fièvre
          type: boolean
        heart_disease:
          description: Si la personne a des problèmes d'hypertension / cardiaques
          type: boolean
        moins_de_15_ans:
          description: Si la personne a moins de 15 ans
          type: boolean
        moins_de_50_ans:
          description: Si la personne a moins de 50 ans
          type: boolean
        moins_de_70_ans:
          description: Si la personne a moins de 70 ans
          type: boolean
      required:
        - moins_de_15_ans
        - moins_de_50_ans
        - au_moins_50_ans
        - entre_50_et_69_ans
        - moins_de_70_ans
        - au_moins_70_ans
        - au_moins_30_imc
        - fever
        - au_moins_39_de_temperature
        - heart_disease
        - facteurs_gravite
        - facteurs_gravite_mineurs
        - facteurs_gravite_majeurs
        - facteurs_pronostique
      title: Statistiques
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Statistiques
    Supplementaires:
      description: >-
        [Questions
        supplémentaires](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#question-suppl%C3%A9mentaire)
      example:
        postal_code: '75000'
      properties:
        postal_code:
          description: Code postal
          type: string
      title: Supplementaires
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Supplementaires
    Symptomes:
      description: >-
        [Questions sur les
        symptômes](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-sympt%C3%B4mes)
      example:
        agueusia_anosmia: true
        breathlessness: true
        cough: true
        diarrhea: true
        feeding: true
        sore_throat_aches: true
        temperature: 37.5
        tiredness: true
      properties:
        agueusia_anosmia:
          description: >-
            Avez-vous noté une forte diminution de votre goût ou de l’odorat ces
            derniers jours ?
          type: boolean
        breathlessness:
          description: >-
            Dans les dernières 24 heures, avez-vous noté un manque de souffle
            INHABITUEL lorsque vous parlez ou faites un petit effort ?
          type: boolean
        cough:
          description: >-
            Avez-vous une toux ou une augmentation de votre toux habituelle ces
            derniers jours ?
          type: boolean
        diarrhea:
          description: >-
            Avez-vous de la diarrhée ces dernières 24 heures (au moins 3 selles
            molles) ?
          type: boolean
        feeding:
          description: >-
            Êtes-vous dans l’impossibilité de vous alimenter ou boire DEPUIS 24
            HEURES OU PLUS ?
          type: boolean
        sore_throat_aches:
          description: Avez-vous un mal de gorge apparu ces derniers jours ?
          type: boolean
        temperature:
          description: >-
            Pensez-vous avoir eu de la fièvre ces derniers jours (frissons,
            sueurs) ? Quelle est votre température ?
          type: number
        tiredness:
          description: >-
            Avez-vous une fatigue inhabituelle ces derniers jours ? Cette
            fatigue vous oblige-t-elle à vous reposer plus de la moitié de la
            journée ?
          type: boolean
      title: Symptomes
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Symptomes
security: []
tags: []

